version: '3.7'
services:
  company_templatez_api:
    image: 'company_templatez_api_${IMAGE_SUFFIX}'
    restart: unless-stopped
    ports: 
      - '${ENDPOINT_HTTP_API_PORT}:80'
    environment:
      - ASPNETCORE_ENVIRONMENT